# clone repo from github
# FROM node 

# WORKDIR /developer/nodejs/app_from_github


# RUN apt-get update && apt-get install -y git

# directory name and then where to clone dot (.) represenrs current directory 
# RUN git clone https://github.com/amit101999/Todo-List-App.git .

# set up the environment varible
ENV PORT 3000
